Data Preprocessing

In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

dataset = pd.read_csv('Wine.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature-scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---

Applying PCA (before training)

In [12]:
from sklearn.decomposition import PCA

# to get the ideal no. of components, we first start with 2 and go on increasing and seeing what kind of results we get
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.65627164 0.34372836]


---

Training Logistic Regression model on Training set

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

---

Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(y_pred)

[1 3 2 1 2 1 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]


In [15]:
print(y_test)

[1 3 2 1 2 2 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]


---

Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

# 3*3 confusion matrix since we have three classes, 1,2,3

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


0.9722222222222222